config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admin'
  devise_for :users, path: ''

  authenticated :admin do
    get 'user/:id' => 'dashboard#user'
    root to: "dashboard#admin", as: :admin_root
  end

  authenticated :user do
    root to: "dashboard#user", as: :user_root
  end

  root to: 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user=nil)
    user ||= User.new
    if user.is_a? Admin
      can :manage, :all
    elsif user.is_a? User
      can :manage, user
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { render nothing: true, status: :forbidden }
      format.html { render text: exception.message, status: :forbidden }
    end
  end

  protected
  def authenticate_user_or_admin!
    redirect_to new_user_session_url unless user_signed_in? or admin_signed_in?
  end

  def current_ability
    if admin_signed_in?
      @current_ability ||= Ability.new(current_admin)
    else
      @current_ability ||= Ability.new(current_user)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!, only: :admin
  before_action :authenticate_user_or_admin!, only: :user
  load_and_authorize_resource :user, parent: false, only: :user, if: :admin_signed_in?

  def index
    respond_to do |format|
      format.html { render }
    end
  end

  def admin
    respond_to do |format|
      format.html { render layout: 'admin' }
    end
  end

  def user
    @user ||= current_user
    respond_to do |format|
      format.html { render layout: 'user' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_menu
    render "layouts/#{navbar_menu_view}"
  end

  private
  def navbar_menu_view
    if user_signed_in?
      "user_navbar_menu"
    elsif admin_signed_in?
      "admin_navbar_menu"
    else
      "navbar_menu"
    end
  end

end

app/views/dashboard/admin.html.slim
h1 Dashboard#admin
p Find me in app/views/dashboard/admin.html.slim

app/views/dashboard/index.html.slim
h1 Dashboard#index
p Find me in app/views/dashboard/index.html.slim

app/views/dashboard/user.html.slim
h1 Dashboard#user
p Find me in app/views/dashboard/user.html.slim

app/views/layouts/_admin_navbar_menu.html.slim
ul.nav.navbar-nav
  li class="#{(params[:controller] == 'dashboard') ? 'active' : ''}" = link_to t('menu.home'), admin_root_url
  li
    a href='#' = t('menu.messages')
  li.dropdown
    a.dropdown-toggle data-toggle='dropdown' href='#'
      = t('menu.profile')
      b.caret
    ul.dropdown-menu
      li
        a href='#' = t('menu.details')
      li
        a href='#' = t('menu.licensing')
      li
        a href='#' = t('menu.education')
  li
    a href='#' = t('menu.reports')
  li class="#{(params[:controller] == 'admin') ? 'active' : ''}" = link_to t('menu.admin'), '#'
  li class="#{(params[:controller] == 'help') ? 'active' : ''}" = link_to t('menu.help'), '#'
ul.nav.navbar-nav.navbar-right
  li
    p.navbar-text.avatar
      = image_tag(current_admin.try(:avatar_url), size: '30x30')
      | &nbsp;
      = link_to "#{current_admin.email}&nbsp;".html_safe, edit_admin_password_url
      = link_to '<span class=\'glyphicon glyphicon-cog\'></span>'.html_safe, edit_admin_password_url
      | &nbsp;&nbsp;|&nbsp;
      = link_to t('menu.logout').html_safe, destroy_admin_session_url, method: 'delete'

app/views/layouts/_dashboard_navbar.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-target='#navbar' data-toggle='collapse' type='button' aria-expanded="false"
        span.sr-only Toggle Navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to page_name, root_url, class: 'navbar-brand'
    #navbar.collapse.navbar-collapse
      = render menu

app/views/layouts/_navbar_menu.html.slim
ul.nav.navbar-nav
  li class="#{(params[:controller] == 'dashboard') ? 'active' : ''}" = link_to t('menu.home'), root_url
  li class="#{(params[:controller] == 'help') ? 'active' : ''}" = link_to t('menu.help'), '#'
- unless devise_controller?
  ul.nav.navbar-nav.navbar-right
    li
      p.navbar-text
        | &nbsp;
        = link_to t('menu.sign_in').html_safe, new_user_session_url
        | &nbsp;|&nbsp;
        = link_to t('menu.sign_up').html_safe, new_user_registration_url

app/views/layouts/_notifications.html.slim
.row
  .col-sm-12
    - if notice
      .alert.alert-info.alert-dismissable role="alert"
        button.close data-dismiss="alert" aria-label="Close" type="button"
          span aria-hidden="true" &times;
        = notice
    - if alert
      .alert.alert-danger.alert-dismissable role="alert"
        button.close data-dismiss="alert" aria-label="Close" type="button"
          span aria-hidden="true" &times;
        = alert

app/views/layouts/_user_navbar_menu.html.slim
ul.nav.navbar-nav
  li class="#{(params[:controller] == 'dashboard') ? 'active' : ''}" = link_to t('menu.home'), user_root_url
  li
    a href='#' = t('menu.messages')
  li
    a href='#' = t('menu.reports')
  li class="#{(params[:controller] == 'admin') ? 'active' : ''}" = link_to t('menu.admin'), '#'
  li class="#{(params[:controller] == 'help') ? 'active' : ''}" = link_to t('menu.help'), '#'
  li.dropdown
    a.dropdown-toggle data-toggle='dropdown' href='#'
      = t('menu.profile')
      | &nbsp;
      span.fa.fa-caret-down
    ul.dropdown-menu
      li
        a href='#' = t('menu.details')
      li
        a href='#' = t('menu.licensing')
      li
        a href='#' = t('menu.education')
ul.nav.navbar-nav.navbar-right
  li
    p.navbar-text.avatar
      = image_tag(@user.try(:avatar_url), size: '30x30')
      | &nbsp;
      = link_to edit_user_registration_path do
        = @user.email.html_safe
        | &nbsp;
        span.fa.fa-cog
  li
    = link_to t('menu.sign_out').html_safe, destroy_user_session_path, method: 'delete'

app/views/layouts/admin.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    meta[name="description" content=""]
    meta[name="author" content=""]
    title
      | SiteFull
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/dashboard_navbar', page_name: "SiteFull Admin", menu: "layouts/admin_navbar_menu"
    .container
      = render 'layouts/notifications'
      .row
        .col-sm-12
          = yield

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    meta[name="description" content=""]
    meta[name="author" content=""]
    title
      | SiteFull
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/dashboard_navbar', page_name: "SiteFull Website", menu: "layouts/navbar_menu"
    .container
      = render 'layouts/notifications'
      .row
        - if devise_controller?
          .col-sm-4.col-sm-offset-4
            = yield
        - else
          .col-sm-12
            = yield

app/views/layouts/user.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    meta[name="description" content=""]
    meta[name="author" content=""]
    title
      | SiteFull
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/dashboard_navbar', page_name: "SiteFull User", menu: "layouts/user_navbar_menu"
    .container
      = render 'layouts/notifications'
      .row
        .col-sm-12
          = yield